//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownFormMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movies
    {
        public int id { get; set; }
        public string MovieName { get; set; }
    }
}
